### ISSUE TITLE
第九章 第220页，重复了一个 LocalStorage

### ISSUE THREAD

**Issue by pengisgood** [ng-book2/book#13]
>有很多种方法可以将数据应用到你的应用之中：
> AJAX HTTP请求
> Websocket
> Indexdb
> LocalStorage
> **LocalStorage**
> Server Worker

请见引用中的**粗体**行

**Comment by asnowwolf** [comment]
已接受，谢谢

**Comment by wkylin** [comment]
数据架构涉及的问题如下。这个。应改成：
