### ISSUE TITLE
第1章 第4页 使用ng new命令创建带下划线"_"的项目名报错

### ISSUE THREAD

**Issue by JonnBox** [ng-book2/book#5]
1. 本人使用最新版的angular-cli版本为1.0.1，angular版本为4.0.0
2. 在使用命令`ng new angular2_hello_world`创建项目时报错，原因大概是新版不支持带下划线`_`的项目名称，修改为`ng new angular2-hello-world`后正常。

**Comment by JonnBox** [comment]
报错的信息是：

> Project name "angular2_hello_world" is not valid. New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.

**Comment by JonnBox** [comment]
在第1章 第23页的第二个项目`angular2_reddit`也会报同样的错，应该是angular-cli升级版本后对项目名有了更加严格的约束，修改为`angular2-reddit`正常。

**Comment by asnowwolf** [comment]
好，多谢！我试验后就添加勘误。

**Comment by asnowwolf** [comment]
已改正。
