### ISSUE TITLE
第7章 music应用，`https://api.spotify.com`接口会有跨域限制，配置proxy.conf.json

### ISSUE THREAD

**Issue by twolun** [ng-book2/book#9]
### 2. 修改package.json命令
```json
"start": "ng serve --proxy-config proxy.conf.json",
```

### 3. 执行
```bash
npm start
```

[demo地址](https://github.com/twolun/ng-book-4/tree/master/music) ->

**Comment by milklook** [comment]
proxy.conf.json文件怎么配置

**Comment by twolun** [comment]
配置target就行了

**Comment by kuangshp** [comment]
可以参考我这里配置处理跨越http://blog.csdn.net/kuangshp128/article/details/71909331

**Comment by asnowwolf** [comment]
已接受，谢谢！
